### ISSUE TITLE
Fix ejs syntax error!

### ISSUE THREAD

**Issue by JugurtaO** [JugurtaO/JO-hikes#2]
Hey there,

Currently, I'm looking for someone who can help me to fix ejs syntax error at my **trails.ejs file line 106**.
file path= "views/trails.ejs"
I returned the trails object from the server to build my web page with EJS and my goal is to store it in a data structure in the front end _**so that I can manipulate it again in a script which will be executed on the client side**_. 

On this I created a script and unfortunately the syntax I used for my trails object is not good in it.

best regards.

**Comment by Dhanesh539** [comment]
I'm happy to help, but to address the specific EJS syntax error on line 106 of your "trails.ejs" file, I'll need to see the relevant code in that file. Please provide the code from around line 106 so that I can assist you in identifying and fixing the issue.

**Comment by JugurtaO** [comment]
@Dhanesh539  Thank you for your contribution,  below you'll find the code around line 106:
 

![Screenshot from 2023-10-19 23-04-43](https://github.com/JugurtaO/GoHiking/assets/98745935/d4002d1c-029e-41c8-af62-c0bf2132b060)
